version: '3.9'

services:
  # MySQL database
  mysql:
    image: mysql:5.7
    container_name: mysql_wp
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # WordPress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: mysql_wp:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password_here
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/sofav_photo_gallery
    restart: always

volumes:
  mysql_data:
  wordpress: 